config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
 
  devise_for :users, :path_prefix => 'my'
  resources :prospects
  resources :customers
  resources :stages
  resources :roles
  resources :users

   root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.role_id == 1
        can :manage, [Prospect,User,Role,Stage]
        can [:read,:update,:destroy], [Customer]
    elsif user.role_id == 2
        can [:create,:read,:update], [Prospect]
    end 
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	belongs_to :user
end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
	belongs_to :stage
	belongs_to :user, class_name: 'User'

	before_create :assign_stage
	after_save :make_as_customer, if: :stage_is_won

	validates_presence_of :full_name, :email, :phone, :location, :stage_id, :managed_by
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	validates_numericality_of :phone
	validates_uniqueness_of :phone, :email
	validates :phone, length: { is: 10 }

	private

		def stage_is_won
			self.stage_id == 3 ? true : false
		end

		def assign_stage
			self.stage_id = Stage.find_by(name: "New Opportunity").id
		end

		def make_as_customer
			if (self.stage_id == Stage.find_by(name: "Won").id) && Customer.find_by(email: self.email).nil?
				Customer.create(full_name: self.full_name, email: self.email, phone: self.phone, location: self.location, managed_by: self.managed_by)
			end
		end
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/stage.rb
class Stage < ActiveRecord::Base
	has_many :prospects

	validates_presence_of :name, :description, :interest_level
	validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :invitable,
         :rememberable, :trackable, :validatable

  belongs_to :role
  has_many :prospects, foreign_key: :managed_by
  has_many :customers, foreign_key: :managed_by

  validates_presence_of :full_name, :phone, :role_id
  validates_numericality_of :phone
  validates_uniqueness_of :phone
  validates :phone, length: { is: 10 }
  
  def role? role
      self.role.name == role
  end

  def password_required?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user! #to call authentication before action

  before_filter :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :phone, :role_id])
  	end 
  	#to permit additional parameters (the lazy way)

  	
  		rescue_from CanCan::AccessDenied do |exception|
	      respond_to do |format|
	        format.json { head :forbidden, content_type: 'text/html' }
	        format.html { redirect_to main_app.root_url, notice: 'You are not authorised to access this page' }
	        format.js   { head :forbidden, content_type: 'text/html' }
	      end
    	end
	
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

	load_and_authorize_resource
	
	def index
		@customers = Customer.all
	end

	def show
		@customer = Customer.find(params[:id])
	end

	def edit
		@customer = Customer.find(params[:id])
	end

	def update
		@customer = Customer.find(params[:id])
		if @customer.update_attributes(customer_params)
			redirect_to customer_path(@customer), notice:" successfully updated"
		else
			render action: "edit"
		end
	end

	def destroy
		@customer = Customer.find(params[:id])
		if @customer.destroy
			redirect_to customers_path, notice: "Successfully seleted deleted customer"
	
		else
		redirect_to :back
		end
	end

	private

	def customer_params
		params[:customer].permit(:full_name, :email, :phone, :location, :managed_by)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	@prospects = (current_user.role? "Sales Manager") ? Prospect.all : current_user.prospects
  	@customers = (current_user.role? "Sales Manager") ? Customer.all : current_user.customers
  	@users = User.all
  	@stages = Stage.all
  	@roles = Role.all
  end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
	
	before_action :authenticate_user!
	load_and_authorize_resource

	def index
		@prospects = (current_user.role? "Sales Manager") ? Prospect.all : current_user.prospects
	end

	def new
		@prospect = Prospect.new
	end

	def create
		@prospects = (current_user.role? "Sales Manager") ? Prospect.all : current_user.prospects
		@prospect = Prospect.new(prospect_params)
		@prospect.save
	end

	def show
		@prospect = Prospect.find(params[:id])
	end

	def edit
		@prospect = Prospect.find(params[:id])
	end

	def update
		@prospect = Prospect.find(params[:id])
		if @prospect.update_attributes(prospect_params)
			redirect_to prospects_path, notice:" successfully updated"
		else
			render action: "edit"
		end
	end

	def destroy
		@prospect = Prospect.find(params[:id])
		@prospect.destroy
	end

	private

	def prospect_params
		params[:prospect].permit(:full_name, :email, :phone, :location, :stage_id, :managed_by)
	end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

	load_and_authorize_resource
	
	def index
		@roles = Role.all
	end
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController

	load_and_authorize_resource
	
	def index
		@stages = Stage.all
	end

	def new
		@stage = Stage.new
	end

	def create
		@stage = Stage.new(stage_params)
		@stage.save
	end

	def show
		@stage = Stage.find(params[:id])
	end

	def edit
		@stage = Stage.find(params[:id])
	end

	def update
		@stage = Stage.find(params[:id])
		if @stage.update_attributes(stage_params)
			redirect_to stages_path, notice:" successfully updated"
		else
			render action: "edit"
		end
	end

	def destroy
		@stage = Stage.find(params[:id])
		@stage.destroy
	end

	private

	def stage_params
		params[:stage].permit(:name, :description, :interest_level)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	load_and_authorize_resource
	
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
			User.invite!(user_params)
		@user.save
		# binding.pry
		# if @user.errors.empty?
		# end
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to users_path, notice:" Successfully updated user"
		else
			render action: "edit"
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
	end

	private

	def user_params
		params[:user].permit(:email, :full_name, :phone, :role_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/prospects/_prospects.html.erb
<table id="table">
  <thead>
    <tr>
      <th>Sl no</th>
      <th>Full Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Location</th>
      <th>Stage</th>
      <th>Managed By</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prospects.each_with_index do |prospect, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= prospect.full_name %></td>
            <td><%= prospect.email %></td>
            <td><%= prospect.phone %></td>
            <td><%= prospect.location %></td>
            <td><%= prospect.stage.try(:name) %></td>
            <td><%= User.find(prospect.managed_by).full_name if User.where(id: prospect.managed_by).exists? %></td> 
            <td><%= link_to edit_prospect_path(prospect), class: "button is-info" do %> Edit <% end %></td>
            <td><%= link_to prospect_path(prospect), method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: "button is-danger" do %> Delete <% end %></td>
          </tr>
        <% end %>
  </tbody>
</table>

app/views/prospects/index.html.erb
<div class="container is-fluid">

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

 <div class="columns">
  <div class="column is-9">
    <h2 class="title is-3">Prospect Details </h2>
  </div>
  <div class="column is-3">
      <h2 class="title is-3">Add New Prospect</h2>
  </div>
</div>

<div class="columns">
  <div class="column is-9">

	  	<% if @prospects.empty? %>

	  	<table class="table is-bordered is-striped" id="table">
		  	<thead>
				<tr>
					<th>Sl.no</th>
					<th>Full Name</th>
					<th>Email</th>
					<th>Phone</th>
					<th>Location</th>
					<th>Stage</th>
					<th>Managed by</th>
				</tr>
			</thead>
	  	</table>
	   		
	  	<% else %>

	  	<table class="table is-bordered is-striped" id="table">
			<thead>
				<tr>
					<th>Sl.no</th>
					<th>Full Name</th>
					<th>Email</th>
					<th>Phone</th>
					<th>Location</th>
					<th>Stage</th>
					<th>Managed by</th>
					<th colspan="2"></th>
				</tr>
			</thead>

			<tbody>
				<% @prospects.each_with_index do |prospect, index| %>
					<tr id="prospect_<%= prospect.id %>">
						<td><%= index + 1 %></td>
						<td><%= prospect.full_name %></td>
						<td><%= prospect.email %></td>
						<td><%= prospect.phone %></td>
						<td><%= prospect.location %></td>
						<td><%= prospect.stage.try(:name) %></td>
					  	<td><%= User.find(prospect.managed_by).full_name if User.where(id: prospect.managed_by).exists? %></td> 
						<td><%= link_to edit_prospect_path(prospect), class: "button is-info" do %> Edit <% end %></td>
						<% if can? :delete, Prospect.new %> 
						<td><%= link_to prospect_path(prospect), method: :delete, data: { confirm: 'Are you sure?' , remote: true}, class: "button is-danger" do %> Delete <% end %></td>
						<% end %>
					</tr>
				<% end %>
			</tbody>
		</table>
		<% end %>
  </div>


  <div class="column is-3">

    <div id="errors">
  	</div>


  	<div class="index-form">

  		<%= form_for Prospect.new,remote: true do |f| %>

			<div class="form-styling">

				<div class="wrap">
	  				<div>
	    				<label for="prospect_full_name">Full Name</label>
	    				<%= f.text_field :full_name, id: "prospect_full_name", class: "cool" %><br>
	  				</div>
	  				<span id="prospectNameError"></span>

	  				<div>
	    				<label for="prospect_email">Email</label>
	    				<%= f.text_field :email, id: "prospect_email", class: "cool" %><br>
	  				</div>
	  				<span id="prospectEmailError"></span>

	  				<div>
	    				<label for="stage_interest_level">Phone</label>
	    				<%= f.text_field :phone, id: "prospect_phone", class: "cool" %><br>
	  				</div>
	  				<span id="prospectPhoneError"></span>

	  				<div>
	    				<label for="prospect_location">Location</label>
	    				<%= f.text_field :location, id: "prospect_location", class: "cool" %><br>
	  				</div>
	  				<span id="prospectLocationError"></span>
				</div>
			</div>

				<div class="columns">
			  		<div class="column is-5">
			    		<%= f.label :stage %>
			  		</div>
			  		<div class="column is-7">
			     		<%= f.collection_select :stage_id, Stage.all, :id, :name %>
			     		<%= f.hidden_field :stage_id, value: 1 %>
			  		</div>
				</div>

				<div class="columns">
			  		<div class="column is-5">
			    		<%= f.label :managed_by %>
			  		</div>
			  		<div class="column is-7">
			     		<%= f.collection_select :managed_by, User.all, :id, :full_name, prompt: "Select who manages" %>
			  		</div>
				</div>

				<div class="columns">
			  		<div class="column is-4 is-offset-6">
			    		<%= f.submit "Submit", class: "button is-success"%>
			  		</div>
				</div>
		<% end %>
	</div>

	<div id="noticeMsg">
  	</div>

  </div>

 </div>
</div>


<script>

	$('input').on('focusin', function() {
	  $(this).parent().find('label').addClass('active');
	});

	$('input').on('focusout', function() {
	  if (!this.value) {
	    $(this).parent().find('label').removeClass('active');
	  }
	});

	var prospectNameHandle = document.getElementById('prospect_full_name');
	var prospectEmailHandle = document.getElementById('prospect_email');
	var prospectPhoneHandle = document.getElementById('prospect_phone');
	var prospectLocationHandle = document.getElementById('prospect_location');

	var prospectNameErrorHandle = document.getElementById('prospectNameError');
	var prospectEmailErrorHandle = document.getElementById('prospectEmailError');
	var prospectPhoneErrorHandle = document.getElementById('prospectPhoneError');
	var prospectLocationErrorHandle = document.getElementById('prospectLocationError');

	var stageHandle = document.getElementById('prospect_stage_id');
	stageHandle.disabled = true; 

	prospectNameHandle.onblur = function(){
	  if(prospectNameHandle.value.length == ""){
	    prospectNameErrorHandle.innerHTML = "cant be blank";
	  }
	  else{
	    prospectNameErrorHandle.innerHTML = "";
	  }
	}

	prospectEmailHandle.onblur = function(){
	  if(prospectEmailHandle.value.length == ""){
	    prospectEmailErrorHandle.innerHTML = "cant be blank";
	  }
	  else if(!validateEmail(prospectEmailHandle.value)){
	    prospectEmailErrorHandle.innerHTML = "invalid email format";
	  }
	  else{
	    prospectEmailErrorHandle.innerHTML = "";
	  }
	}

	prospectPhoneHandle.onblur = function(){
	  if(prospectPhoneHandle.value.length == ""){
	    prospectPhoneErrorHandle.innerHTML = "cant be blank";
	  }

	  else if(prospectPhoneHandle.value.length != 10){
	    prospectPhoneErrorHandle.innerHTML = "phone number should be 10 digits";
	  }

	  else if (isNan(prospectPhoneHandle.value)){
	    prospectPhoneErrorHandle.innerHTML = "phone number should be a number";
	  }

	  else{
	    prospectPhoneErrorHandle.innerHTML = "";
	  }
	}


	prospectLocationHandle.onblur = function(){
	  if(prospectLocationHandle.value.length == ""){
	    prospectLocationErrorHandle.innerHTML = "cant be blank";
	  }
	  else{
	    prospectLocationErrorHandle.innerHTML = "";
	  }
	}


	function validateEmail(email) {
	    var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
	    return re.test(email);
	}

</script>

app/views/stages/_stages.html.erb
<table id="table">
  <thead>
    <tr>
      <th>Sl.no</th>
      <th>Name</th>
      <th>Description</th>
      <th>Interest Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   <tbody>
        <% Stage.all.each_with_index do |stage, index| %>
          <tr id="stage_<%= stage.id %>">
            <td><%= index + 1 %></td>
            <td><%= stage.name %></td>
            <td><%= stage.description %></td>
            <td><%= stage.interest_level %></td>
            <td><%= link_to edit_stage_path(stage), class: "button is-info" do %> Edit <% end %></td>
            <% if stage.id > 4 %>
            <td><%= link_to stage_path(stage), method: :delete, data: { confirm: 'Are you sure?', remote: true } , class: "button is-danger" do %> Delete <% end %></td>
            <% end %> 
          </tr>
        <% end %>
      </tbody>
  </tbody>
</table>

app/views/stages/index.html.erb
<div class="container is-fluid">

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

 <div class="columns">
  <div class="column is-8">
    <h2 class="title is-3">Stage Details</h2>
  </div>
  <div class="column is-4">
      <h2 class="title is-3">Add New Stage</h2>
  </div>
</div>



<div class="columns">
  <div class="column is-8">

  		<% if @stages.empty? %>

  		<table class="table is-bordered is-striped" id="table">
  			<thead>
				<tr>
					<td>Sl.no</td>
					<td>Name</td>
					<td>Description</td>
					<td>Interest Level</td>
				</tr>
			</thead>

  		</table>
   			
		<% else %>
		
	  	<table class="table is-bordered is-striped" id="table">
			<thead>
				<tr>
					<td>Sl.no</td>
					<td>Name</td>
					<td>Description</td>
					<td>Interest Level</td>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @stages.each_with_index do |stage, index| %>
					<tr id="stage_<%= stage.id %>">
						<td><%= index + 1 %></td>
						<td><%= stage.name %></td>
						<td><%= stage.description %></td>
						<td><%= stage.interest_level %></td>
						<td><%= link_to edit_stage_path(stage), class: "button is-info" do %> Edit <% end %></td>
						<% if stage.id > 4 %>
						<td><%= link_to stage_path(stage), method: :delete, data: { confirm: 'Are you sure?', remote: true } , class: "button is-danger" do %> Delete <% end %></td>
						<% end %>
					</tr>
				<% end %>
			</tbody>
		</table>
  </div>

  <div class="column is-4">

    <div id="errors">
  	</div>

	<div class="index-form">

		<div class="form-styling">

  			<%= form_for Stage.new,remote: true do |f| %>

				<div class="wrap">
	  				<div>
	    				<label for="stage_name">Name</label>
	    				<%= f.text_field :name, id: "stage_name", class: "cool" %><br>
	  				</div>
	  				<span id="stageNameError"></span>

	  				<div>
	    				<label for="stage_description">Description</label>
	    				<%= f.text_field :description, id: "stage_description", class: "cool" %><br>
	  				</div>
	  				<span id="stageDescriptionError"></span>

	  				<div>
	    				<label for="stage_interest_level">Interest Level</label>
	    				<%= f.text_field :interest_level, id: "stage_interest_level", class: "cool" %><br>
	  				</div>
	  				<span id="stageInterestLevelError"></span>
				</div>
	

				<div class="columns">
			  		<div class="column is-4 is-offset-8">
			    		<%= f.submit "Submit", class: "button is-success"%>
			  		</div>
				</div>

			<% end %>
		</div>
	</div>

	<div id="noticeMsg">
  	</div>

  </div>
 </div>

<% end %>
</div>


<script>

	$('input').on('focusin', function() {
	  $(this).parent().find('label').addClass('active');
	});

	$('input').on('focusout', function() {
	  if (!this.value) {
	    $(this).parent().find('label').removeClass('active');
	  }
	});
	
	var stageNameHandle = document.getElementById('stage_name');
	var stageDescriptionHandle = document.getElementById('stage_description');
	var stageInterestLevelHandle = document.getElementById('stage_interest_level');

	var stageNameErrorHandle = document.getElementById('stageNameError');
	var stageDescriptionErrorHandle = document.getElementById('stageDescriptionError');
	var stageInterestLevelErrorHandle = document.getElementById('stageInterestLevelError');



	stageNameHandle.onblur = function(){
	  if(stageNameHandle.value.length == ""){
	    stageNameErrorHandle.innerHTML = "cant be blank";
	  }
	  else{
	    stageNameErrorHandle.innerHTML = "";
	  }
	}

	stageDescriptionHandle.onblur = function(){
	  if(stageDescriptionHandle.value.length == ""){
	    stageDescriptionErrorHandle.innerHTML = "cant be blank";
	  }
	  else{
	    stageDescriptionErrorHandle.innerHTML = "";
	  }
	}

	stageInterestLevelHandle.onblur = function(){
	  if(stageInterestLevelHandle.value.length == ""){
	    stageInterestLevelErrorHandle.innerHTML = "cant be blank";
	  }
	  else{
	    stageInterestLevelErrorHandle.innerHTML = "";
	  }
	}

</script>



 

app/views/users/_users.html.erb
<table id="table">
  <thead>
    <tr>
      <th>Sl no</th>
      <th>Full Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% User.all.each_with_index do |user, index| %>
          <tr id="user_<%= user.id %>">
            <td><%= index + 1 %></td>
            <td><%= user.full_name %></td>
            <td><%= user.email %></td>
            <td><%= user.phone %></td>
            <td><%= user.role.try(:name) %></td>
            <td><%= link_to edit_user_path(user), class: "button is-info" do %> Edit <% end %></td>
           <% unless user.role_id == 1 %>
            <td><%= link_to user_path(user), method: :delete, data: { confirm: 'Are you sure?' , remote: true}, class: "button is-danger" do %> Delete <% end %></td>
            <% end %>
          </tr>
        <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<div class="container is-fluid">

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

 <div class="columns">
  <div class="column is-9">
    <h2 class="title is-3">User Details </h2>
  </div>
  <div class="column is-3">
 <h2 class="title is-3">Add New User</h2>
  </div>
</div>

<div class="columns">
  <div class="column is-9">

  		<% if @users.empty? %> 
  		
  		<table class="table is-bordered is-striped" id="table">
  			<thead>
				<tr>
					<th>Sl.no</th>
					<th>Full Name</th>
					<th>Email</th>
					<th>Phone</th>
					<th>Role</th>
				</tr>
			</thead>
  		</table>
   			
		<% else %>

	  	<table class="table is-bordered is-striped" id="table">
			<thead>
				<tr>
					<th>Sl.no</th>
					<th>Full Name</th>
					<th>Email</th>
					<th>Phone</th>
					<th>Role</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each_with_index do |user, index| %>
					<tr id="user_<%= user.id %>">
						<td><%= index + 1 %></td>
						<td><%= user.full_name %></td>
						<td><%= user.email %></td>
						<td><%= user.phone %></td>
						<td><%= user.role.try(:name) %></td>	
						<td><%= link_to edit_user_path(user), class: "button is-info" do %> Edit <% end %></td>
						<% unless user.role_id == 1 %>
						<td><%= link_to user_path(user), method: :delete, data: { confirm: 'Are you sure?' , remote: true}, class: "button is-danger" do %> Delete <% end %></td>
						<% end %>
					</tr>
				<% end %>
			</tbody>
		</table>

  </div>

  <div class="column is-3">

    <div id="errors">
  	</div> 

  	<div class="index-form">

		<%= form_for User.new,remote: true do |f| %>

			<div class="form-styling">

				<div class="wrap">
	  				<div>
	    				<label for="user_full_name">Full Name</label>
	    				<%= f.text_field :full_name, id: "user_full_name", class: "cool" %><br>
	  				</div>
	  				<span id="userNameError"></span>

	  				<div>
	    				<label for="user_email">Email</label>
	    				<%= f.text_field :email, id: "user_email", class: "cool" %><br>
	  				</div>
	  				<span id="userEmailError"></span>

	  				<div>
	    				<label for="user_phone">Phone</label>
	    				<%= f.text_field :phone, id: "user_phone", class: "cool" %><br>
	  				</div>
	  				<span id="userPhoneError"></span>

				</div>

			</div>

				<div class="columns">
			  		<div class="column is-2">
			    		<%= f.label :role_id %>
			  		</div>
			  		<div class="column is-10">
			     		<%= f.collection_select :role_id, Role.all, :id, :name, prompt: "Select Role" %>
			     		<span id="userRoleError"></span>
			  		</div>
				</div>

				<div class="columns">
			  		<div class="column is-4 is-offset-8">
			    		<%= f.submit "Submit", class: "button is-success"%>
			  		</div>
				</div>

		<% end %>
	</div>

	<div id="noticeMsg">
  	</div>

  </div>
 </div>

<% end %>
</div>


<script>

	$('input').on('focusin', function() {
	  $(this).parent().find('label').addClass('active');
	});

	$('input').on('focusout', function() {
	  if (!this.value) {
	    $(this).parent().find('label').removeClass('active');
	  }
	});
	
	var userNameHandle = document.getElementById('user_full_name');
	var userEmailHandle = document.getElementById('user_email');
	var userPhoneHandle = document.getElementById('user_phone');

	var userNameErrorHandle = document.getElementById('userNameError');
	var userEmailErrorHandle = document.getElementById('userEmailError');
	var userPhoneErrorHandle = document.getElementById('userPhoneError');

	userNameHandle.onblur = function(){
	  if(userNameHandle.value.length == ""){
	    userNameErrorHandle.innerHTML = "cant be blank";
	  }
	  else{
	    userNameErrorHandle.innerHTML = "";
	  }
	}

	userEmailHandle.onblur = function(){
	  if(userEmailHandle.value.length == ""){
	    userEmailErrorHandle.innerHTML = "cant be blank";
	  }
	  else if(!validateEmail(userEmailHandle.value)){
	    userEmailErrorHandle.innerHTML = "invalid email format";
	  }
	  else{
	    userEmailErrorHandle.innerHTML = "";
	  }
	}

	userPhoneHandle.onblur = function(){
	  if(userPhoneHandle.value.length == ""){
	    userPhoneErrorHandle.innerHTML = "cant be blank";
	  }
	  else if(userPhoneHandle.value.length == ""){
	    userEmailErrorHandle.innerHTML = "invalid email format";
	  }
	  else{
	    userPhoneErrorHandle.innerHTML = "";
	  }
	}

	function validateEmail(email) {
	    var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
	    return re.test(email);
	}

</script>